{ config, pkgs, ... }:

{
  # ---------------------------------------------------------------- Qt ---
  qt = {
    enable = true;
    platformTheme.name = "qt6ct";
  };

  qt.qt6ctSettings = {
    Appearance = {
      color_scheme_path = "${config.home.homeDirectory}/.config/qt6ct/colors/noctalia.conf";
      custom_palette = "true";
      icon_theme = "pixelitos-dark";
      standard_dialogs = "xdgdesktopportal";
      style = "Breeze";
    };

    Fonts = {
      fixed = "\"CozetteVector,12\"";
      general = "\"CozetteVector,12\"";
    };
  };

  # --------------------------------------------------------------- GTK ---
  gtk = {
    enable = true;

    theme = {
      name = "adw-gtk3-dark";
      package = pkgs.adw-gtk3;
    };

    # package omitted - it's nullOr/default null in this HM revision (see
    # modules/misc/gtk/lib.nix's mkThemeType), and null explicitly means
    # "already available in the profile", which ~/.icons is. GTK finds it
    # via the standard search path (~/.icons, ~/.local/share/icons).
    iconTheme.name = "pixora-dark";

    font = {
      name = "CozetteVector";
      size = 12;
    };

    gtk3.extraConfig.gtk-application-prefer-dark-theme = 1;
    gtk4.extraConfig.gtk-application-prefer-dark-theme = 1;
  };

  # home.pointerCursor can't be used here: unlike gtk.iconTheme/gtk.theme,
  # its `package` option (modules/config/home-cursor.nix) has no default
  # and is typed as plain `types.package`, not `nullOr` - it's mandatory,
  # so the whole module doesn't work without installing a package. Falling
  # back to what it would have generated by hand: the GTK-side cursor keys
  # via gtk.cursorTheme (package there IS optional, same mkThemeType as
  # iconTheme above) plus the XCURSOR_* session variables it would
  # otherwise have set for everything else.
  gtk.cursorTheme = {
    name = "retrosmart-xcursor-win-ish-violet-shadow";
    size = 32;
  };

  home.sessionVariables = {
    XCURSOR_THEME = "retrosmart-xcursor-win-ish-violet-shadow";
    XCURSOR_SIZE = 32;
  };
}
